### ISSUE TITLE
Use new version of CVODES 3.0 ?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.SimModel.Solver.CVODES.282#6]
We are using 2.8. We missed 2.9 and 3.0
Should not we update?
https://computation.llnl.gov/projects/sundials/cvodes

**Comment by Yuri05** [comment]
At the moment I don't see any urgency for upgrading.
New features in 2.3-3.0 mainly include redesign of CVODE(S) e.g. for easier use of external linear solvers.

**Comment by Yuri05** [comment]
moving to CVODES 4.0
